services:
  app:
    image: ${APP_IMAGE}
  product-service:
      container_name: product

      image: ${DOCKER_IMAGE}
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        SPRING_DATASOURCE_URL: "${DB_HOST}://db:${DB_PORT}/jfs"
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ports:
        - "${HOST_PORT}:8080"
      networks:
        - amigos
  db:
    container_name: jfs-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: jfs
    ports:
      - "5333:5432"
    restart: unless-stopped
    volumes:
      - db:/data/postgres
    networks:
      - amigos

networks:
  amigos:
    driver: bridge

volumes:
  db:
