name: Deploy Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_number:
        description: " the build number to deploy(optional)"
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      #      DOCKER_USERNAME: tjsun0001
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: product-service
      DB_HOST: jdbc:postgresql
      DB_PORT: 5432
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      PG_USER: ${{secrets.PG_USER}}
      PG_PASSWORD: ${{secrets.PG_PASSWORD}}
      DOCKER_COMPOSE_APP_SERVICE_NAME: product-service
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        if: ${{github.event.inputs.build_number == '' }}
        uses: actions/checkout@v4
      - name: Send Slack message with github commit url
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"${{github.event.head_commit.message }} - https://${{ github.repository}}/commit/${{github.sha }}"}' 
          ${{env.SLACK_WEBHOOK_URL}}
      - name: JDK
        if: ${{ github.event.inputs.build_number == '' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Build Number
        run: |
          if [ -n "${{ github.event.inputs.build_number}}" ]; then
            BUILD_NUMBER=${{github.event.inputs.build_number}}
            echo "using provided build number: $BUILD_NUMBER"
          else
            BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
            echo "using generated build number: $BUILD_NUMBER"
          fi
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Check if provided image exists
        if: ${{ github.event.inputs.build_number  != '' }}
        run: |
          IMAGE_NAME="${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:$BUILD_NUMBER"
          echo "checking if $IMAGE_NAME exists"
          if ! docker manifest inspect "$IMAGE_NAME" > /dev/null 2>&1; then
            echo "provided image $IMAGE_NAME does not exist. exiting ..."
            exit 1
          fi
          echo "provided image $IMAGE_NAME exists. âœ…exiting..."
      - name: Maven Clean Verify
        if: ${{ github.event.inputs.build_number  == '' }}
        run: |
          mvn -B -ntp clean package jib:build \
              -Dimage=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
      - name : Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          
      - name: SSH_TO_EC2_and_Deploy
    run: |
      ssh -o StrictHostKeyChecking=no $EC2_PUBLIC_IP_ADDRESS \
      DOCKER_USERNAME="${DOCKER_USERNAME}" BUILD_NUMBER="${BUILD_NUMBER}" 'bash -s' << 'EOF'
      set -euo pipefail
      cd /home/ubuntu/my-mlops-demo

      echo "${BUILD_NUMBER}" > build-number.txt

      docker compose config | sed -n '/product-service:/,/^[^ ]/p'

      docker compose pull product-service
      docker compose rm -sf product-service
      docker compose up -d --no-deps --force-recreate product-service

      docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      # cleanup (demo-friendly)
      docker image prune -af --filter "until=24h"
      docker builder prune -af --filter "until=24h"

      # disk visibility
      lsblk
      df -h /
      docker system df
    EOF


      - name: Send Slack message with status
        if: always()
        run: >
          curl -X POST -H 'Content-type: application/json'
          --data '{"text":"Job status ${{job.status}} - https://${{ github.repository}}/commit/${{github.sha }}"}' 
          ${{env.SLACK_WEBHOOK_URL}}
          
         
          
