name: Deploy Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: tjsun0001
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: product-service
      DOCKER_COMPOSE_APP_SERVICE_NAME: product-service
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
           echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          mvn -B -ntp clean package -DskipTests -DskipITs -DskipUTs=true -DskipITs=true -Djib.skipTests=true
          mvn -B -ntp jib:build -Ddocker.image.tag=$BUILD_NUMBER
      - name : Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
              ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      - name: SSH_TO_EC2_and_Deploy
        run : |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP_ADDRESS 
          echo $BUILD_NUMBER
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $DOCKER_COMPOSE_APP_SERVICE_NAME
            ls
            pwd
            export APP_IMAGE="${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}"
            echo $APP_IMAGE
            docker compose  pull
            docker compose  up -d $DOCKER_COMPOSE_APP_SERVICE_NAME
            docker image prune -f
            docker ps
            echo "BUILD_NUMBER" > build-number.txt
          


