name: Deploy Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
#      DOCKER_USERNAME: tjsun0001
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_NAME: product-service
      DOCKER_COMPOSE_APP_SERVICE_NAME: product-service
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Generate Build Number
        run: |
          BUILD_NUMBER=$(date +'%d%m%Y%H%M%S')
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
           echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build Maven artifact without tests
        run: |
      - name : Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
              ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      - name: SSH_TO_EC2_and_Deploy
        run : |
          mvn -B -ntp clean package jib:build \
          -Dimage=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
#          -Dimage=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${BUILD_NUMBER}
          ssh -o StrictHostKeyChecking=no $EC2_PUBLIC_IP_ADDRESS << EOF
          echo "Inside EC2"
          cd /home/ubuntu
          echo $BUILD_NUMBER
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $DOCKER_COMPOSE_APP_SERVICE_NAME
            ls
            pwd
            export APP_IMAGE="tjsun0001/product-service:latest"
            sudo docker compose  pull
            sudo docker compose  up -d 
            sudo docker image prune -f
            sudo docker ps
            echo "BUILD_NUMBER" > build-number.txt
          EOF


